# Generated by Django 4.2.6 on 2023-10-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rome',
            new_name='Room',
        ),
    ]
